heartbeat.monitors:
- type: http
  urls: ["${MONITOR_URL}"]
  schedule: '@every 5m'
  timeout: 10s
fields:
  project: nodebb
  env: ${PROJECT_ENV}

output.logstash:
  hosts: ["${HEARTBEAT_LOGSTASH_HOST}"]
