metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - filesystem
      - memory
    enabled: true
    period: 10s
    cpu_ticks: false
fields:
  project: nodebb
  env: dev
output.logstash:
  hosts: ["10.225.33.159:5044"]
