metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - filesystem
      - memory
    enabled: true
    period: 10s
    cpu_ticks: false
fields:
  project: nodebb
  env: ${PROJECT_ENV}
output.logstash:
  hosts: ["${LOGSTASH_HOST}"]
