filebeat.prospectors:
- input_type: log
  paths:
    - /root/apps/nodebb/logs/output.log
  fields:
    project: nodebb
    env: dev
output.logstash:
  hosts: ["${LOGSTASH_HOST}"]
logging.level: debug
