metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - filesystem
      - memory
    enabled: true
    period: 60s
    cpu_ticks: false
fields:
  project: nodebb
  env: prod
output.logstash:
  hosts: ["${LOGSTASH_HOST}"]
